### ISSUE TITLE
A command option to export books in PDF files.

### ISSUE THREAD

**Issue by edersong** [BookStackApp/system-cli#14]
I use Bookstack to document all my procedures, but how to get that documentation when the system is down?
I would like to request a way to export books in PDF thru command line in order to export them automatically (cron or scripted basis) to a desired folder for offline emergency access.
Of course, it will be useful for many other situations.
Thank you for the wonderful work so far.

**Comment by ssddanbrown** [comment]
Thanks for the request @edersong, but I wouldn't really look to increase the scope of this CLI to support export tasks too.
This is something that can be achieved via the REST API if desired, and I have an [example script for that here](https://github.com/BookStackApp/api-scripts/tree/main/php-export-all-books).
