### ISSUE TITLE
Feature Request - Specify which branch/tag is used for Init

### ISSUE THREAD

**Issue by cdrfun** [BookStackApp/system-cli#15]
As an administrator and developer, I want to be able to quickly init from any branch and tag, so I can easily test upcoming features in a dedicated environment.

**Comment by ssddanbrown** [comment]
Thanks for the request, but from my perspective only the latest release is officially supported, and I'd like to keep the scope of the CLI on production/supported use-cases. Our other branches are only really for development use, in which case extra tooling/steps is needed in most cases, so the extra step of switching branch manually via git afterwards, for developers that desire this, should not be too much extra work in my view.

**Comment by cdrfun** [comment]
I understand, thanks for clarification.
